server:
  port: 0

spring:
  application:
    name: ms-atendimento
 # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    # Mongo DB
    mongodb:
      host: localhost
      port: 27017
      database: atendimento

#  # Mysql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/easy-clinic?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
#    username: root
#    password: admin123
#  #jpa configuration
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false

## Axon Server
#axon:
#  axonserver:
#    servers: localhost:8124
#  eventhandling:
#    processors:
#      atendimento-group:
#        mode: subscribing

# Queue Messenger
rabbit:
  queue: easy-clinic-queue
  dead-letter: easy-clinic-dead-letter-queue

# Security
security:
  oauth2:
    resource:
      jwt:
        key-value: 99137c50b1d3a4ab8720ac92949af871061534caa

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info
    org:
      axonframework:
        axonserver:
          connector:
            event:
              axon:
                AxonServerEventStore: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"