server:
  port: 9091

# Mongo DB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: paciente

# Axon Server
axon:
  axonserver:
    servers: localhost:8124

# Security
security:
  oauth2:
    resource:
      jwt:
        key-value: 99137c50b1d3a4ab8720ac92949af871061534caa