# Spring
server:
  port: 8761

# Eurika

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-register: false
  instance:
    prefer-ip-address: true
    hostname: localhost

